<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-13T16:23:50 IST" name="Suite" finished-at="2023-02-13T16:25:23 IST" duration-ms="93415">
    <groups>
    </groups>
    <test started-at="2023-02-13T16:23:50 IST" name="Test" finished-at="2023-02-13T16:25:23 IST" duration-ms="93415">
      <class name="tests.LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:23:50 IST" name="setUp" finished-at="2023-02-13T16:24:11 IST" duration-ms="20714" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyInvalidLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:11 IST" name="verifyInvalidLogin" data-provider="getCredentials" finished-at="2023-02-13T16:24:14 IST" duration-ms="3126" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidLogin -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:14 IST" name="tearDwon" finished-at="2023-02-13T16:24:14 IST" duration-ms="447" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:14 IST" name="setUp" finished-at="2023-02-13T16:24:28 IST" duration-ms="13899" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyInvalidLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:28 IST" name="verifyInvalidLogin" data-provider="getCredentials" finished-at="2023-02-13T16:24:30 IST" duration-ms="1508" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[   ]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required123]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at tests.LoginPageTest.verifyInvalidLogin(LoginPageTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidLogin -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:30 IST" name="tearDwon" finished-at="2023-02-13T16:24:30 IST" duration-ms="459" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:30 IST" name="setUp" finished-at="2023-02-13T16:24:53 IST" duration-ms="22604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyInvalidLogin(java.lang.String,java.lang.String)[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:53 IST" name="verifyInvalidLogin" data-provider="getCredentials" finished-at="2023-02-13T16:24:55 IST" duration-ms="1743" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[   ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong ErrorMessage for Blank Username/psasword!!! expected [Required] but found [Required123]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at tests.LoginPageTest.verifyInvalidLogin(LoginPageTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidLogin -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:55 IST" name="tearDwon" finished-at="2023-02-13T16:24:55 IST" duration-ms="375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:24:55 IST" name="setUp" finished-at="2023-02-13T16:25:19 IST" duration-ms="23835" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLogin()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:25:19 IST" name="verifyLogin" finished-at="2023-02-13T16:25:23 IST" duration-ms="3689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:tests.LoginPageTest@338c99c8]" started-at="2023-02-13T16:25:23 IST" name="tearDwon" finished-at="2023-02-13T16:25:23 IST" duration-ms="319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
      </class> <!-- tests.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
